name: Build and Deploy to Prod

on:
  push:
    branches:
        - prod

jobs:
  build_and_preview:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create Frontend .env
        run: |
          cd frontend
          touch .env
          echo NEXT_PUBLIC_FIREBASE_CONFIG=${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG_PROD }} >> .env
      - name: Create Backend .env
        run: |
          cd backend
          touch .env
          echo MONGO_URI=${{ secrets.MONGO_URI_PROD }} >> .env
          echo SERVICE_ACCOUNT_KEY=${{ secrets.SERVICE_ACCOUNT_KEY_PROD }} >> .env
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
          echo APP_FIREBASE_CONFIG=${{ secrets.APP_FIREBASE_CONFIG_PROD }} >> .env
          echo EMAIL_ADDRESS_1=${{ secrets.EMAIL_ADDRESS_1 }} >> .env
          echo PASS_1=${{ secrets.PASS_1 }} >> .env
      - name: Build Frontend
        run: cd frontend && npm ci && npm run build
      - name: Build Backend
        run: |
          cd backend
          npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.SERVICE_ACCOUNT_KEY_PROD }}"
          projectId: pia-database-780ab
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: pintags